export const FETCH_ALL_EMPLOYEES_REQUEST = "FETCH_ALL_EMPLOYEES_REQUEST";
export const FETCH_ALL_EMPLOYEES_SUCCESS = "FETCH_ALL_EMPLOYEES_SUCCESS";
export const FETCH_ALL_EMPLOYEES_FAILURE = "FETCH_ALL_EMPLOYEES_FAILURE";
