export const FETCH_USER_REIMBURSEMENTS_REQUEST =
  "FETCH_USER_REIMBURSEMENT_REQUEST";
export const FETCH_USER_REIMBURSEMENTS_SUCCESS =
  "FETCH_USER_REIMBURSEMENT_SUCCESS";
export const FETCH_USER_REIMBURSEMENTS_FAILURE = "FETCH_REIMBURSEMENT_FAILURE";

export const DELETE_USER_REIMBURSEMENTS_REQUEST =
  "DELETE_USER_REIMBURSEMENT_REQUEST";
export const DELETE_USER_REIMBURSEMENTS_SUCCESS =
  "DELETE_USER_REIMBURSEMENT_SUCCESS";
export const DELETE_USER_REIMBURSEMENTS_FAILURE =
  "DELETE_REIMBURSEMENT_FAILURE";

export const CREATE_USER_REIMBURSEMENT_REQUEST =
  "CREATE_USER_REIMBURSEMENT_REQUEST";
export const CREATE_USER_REIMBURSEMENT_SUCCESS =
  "CREATE_USER_REIMBURSEMENT_SUCCESS";
export const CREATE_USER_REIMBURSEMENT_FAILURE =
  "CREATE_USER_REIMBURSEMENT_FAILURE";
export const CREATE_USER_REIMBURSEMENT_SUCCESS_RESET =
  "CREATE_USER_REIMBURSEMENT_SUCCESS_RESET";

export const FETCH_ALL_REIMBURSEMENTS_REQUEST =
  "FETCH_ALL_REIMBURSEMENTS_REQUEST";
export const FETCH_ALL_REIMBURSEMENTS_SUCCESS =
  "FETCH_ALL_REIMBURSEMENTS_SUCCESS";
export const FETCH_ALL_REIMBURSEMENTS_FAILURE =
  "FETCH_ALL_REIMBURSEMENTS_FAILURE";

export const UPDATE_REIMBURSEMENT_REQUEST = "UPDATE_REIMBURSEMENT_REQUEST";
export const UPDATE_REIMBURSEMENT_SUCCESS = "UPDATE_REIMBURSEMENT_SUCCESS";
export const UPDATE_REIMBURSEMENT_FAILURE = "UPDATE_REIMBURSEMENT_FAILURE";
